### ISSUE TITLE
Local deploy not working (under minishift not either)

### ISSUE THREAD

**Issue by pvi25** [redhat-helloworld-msa/hola#12]
Hi,

I'm quite a newby to all of this, so maybe this is not the right place to put this issue. I want to experiment a bit with redhat minishift and am now trying to deploy helloworld-msa. Aloha I got working in minishift, but I cant get this hola to work in minishift (get a 404 error). So I thought I'd try to first run hola locally (on a RHEL7 VM), but cant get that to work either. 'mvn wildfly-swarm:run' (as mentioned in the readme) doesnt work at all, 'mvn thorntail:run' does get a lot further, but gives following error after a while:
```
2018-12-30 12:42:12,912 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 33) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./: java.lang.IllegalArgumentException: Illegal character in path at index 1: ${env.KEYCLOAK_AUTH_SERVER_URL}
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:84)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
        at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 1: ${env.KEYCLOAK_AUTH_SERVER_URL}
        at java.base/java.net.URI.create(URI.java:883)
        at org.keycloak.adapters.KeycloakDeployment.setAuthServerBaseUrl(KeycloakDeployment.java:135)
        at org.keycloak.adapters.KeycloakDeploymentBuilder.internalBuild(KeycloakDeploymentBuilder.java:135)
        at org.keycloak.adapters.KeycloakDeploymentBuilder.build(KeycloakDeploymentBuilder.java:152)
        at org.keycloak.adapters.undertow.KeycloakServletExtension.handleDeployment(KeycloakServletExtension.java:135)
        at io.undertow.servlet.core.DeploymentManagerImpl.handleExtensions(DeploymentManagerImpl.java:263)
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:153)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:99)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
        ... 6 more

```
Any clue to how this can be solved?

**Comment by pvi25** [comment]
Must do something stupid probably, but I really dont understand what I'm doing wrong. Tried it on RHEL with maven 3.5.6, 3.5.4 and now also with 3.5.3, but they all give the same error. Even tried it on my Ubuntu 18.04 nas with maven 3.5.2 and also that gives exactly the same error.

mvn --version on RHEL7 VM gives:

```
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T20:49:05+01:00)
Maven home: /home/pvi/apache-maven-3.5.3
Java version: 1.8.0_191, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-957.el7.x86_64", arch: "amd64", family: "unix"
```
 Anything wrong with that?

attached the full output of the mvn thorntail:run :
[output.txt](https://github.com/redhat-helloworld-msa/hola/files/2725082/output.txt)

Console also give this message with mvn thorntail:run : Mon Dec 31 17:35:46 CET 2018 INFO [org.wildfly.swarm.bootstrap] (main) Dependencies not bundled; resolving from M2REPO.

Any clue?

**Comment by rafabene** [comment]
I've run it in a RHEL VM and faced the same issue. I don't know the cause but the workaround is to create and empty KEYCLOAK_AUTH_SERVER_URL env var with the command:

> export KEYCLOAK_AUTH_SERVER_URL=""

**Comment by pvi25** [comment]
Thanks, got it working now with the workaround indeed, also under minishift.
